Fix width and height typing and add auto-shipit
selsa-inube/inubekit-grid pull request #5
Opened 2024-03-27 22:42 UTC by cmarin001

This pull request addresses essential enhancements within our application's development ecosystem, focusing on the correction of width and height property typings across components and the integration of an auto-shipit feature for automated deployments. Aimed at refining the codebase and optimizing deployment processes, these updates ensure accurate type definitions for UI elements and a more efficient, automated release workflow.

2024-03-29 17:43 UTC, wfercanas requested changes

2024-03-29 17:43 UTC, wfercanas commented on src/Grid/stories/stories.styles.ts
> +  color: ${inube.palette.neutral.N10};
Let's change this color to a darker one, could be a N100.

2024-03-29 17:43 UTC, wfercanas commented on src/Grid/index.tsx
The build process is including `react/jsx-runtime`

2024-04-01 15:07 UTC, cmarin001 commented on src/Grid/stories/stories.styles.ts
> +  color: ${inube.palette.neutral.N10};
solved

2024-04-01 15:07 UTC, cmarin001 commented on src/Grid/index.tsx
solved

2024-04-01 16:07 UTC, wfercanas approved these changes

2024-04-02 18:10 UTC, JanuarAsprilla commented
![image](https://github.com/selsa-inube/inubekit-grid/assets/140556686/1b027d0b-ebbf-404d-95f3-b52bea2ee7e9)
run the `npm run build` command and check to fix the issues you are having

2024-04-02 18:12 UTC, JanuarAsprilla commented
In the `package.json` you need to implement the guideline, which is to place the `peerDependencies` and the packages that go inside these

2024-04-02 18:25 UTC, JanuarAsprilla approved these changes

2024-04-02 21:07 UTC, wfercanas approved these changes

2024-04-02 21:07 UTC, merged